# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
np.version.version

'1.16.5'

In [7]:
np.__version__

'1.16.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [9]:
# Method 1
a = np.random.random(size=(2,3,5))

array([[[0.02231172, 0.29945747, 0.00463107, 0.48132289, 0.95170162],
        [0.84221344, 0.25186719, 0.48949999, 0.03256431, 0.8463534 ],
        [0.21041523, 0.00141905, 0.27183837, 0.34558973, 0.0278985 ]],

       [[0.26875114, 0.1997851 , 0.26133733, 0.85504941, 0.45061267],
        [0.65189698, 0.7876542 , 0.89486001, 0.27877477, 0.71740643],
        [0.0271388 , 0.84422612, 0.1650754 , 0.12490619, 0.00570087]]])

In [60]:
# Method 2
a = np.array(np.random.randint(0,100,size=(2,3,5)))
a

array([[[62, 89, 82, 25, 56],
        [84, 66, 38, 77, 93],
        [11, 68, 78,  6, 68]],

       [[36, 30, 46, 23, 49],
        [66, 51, 64, 86, 43],
        [66, 41, 56, 31, 16]]])

In [43]:
# Method 3 
r2 = np.array(np.random.random_sample(size=(2,3,5)))
r2

array([[[0.16043468, 0.77541962, 0.72106259, 0.65491057, 0.60341458],
        [0.12519489, 0.4803024 , 0.27470588, 0.76267454, 0.92519635],
        [0.04074976, 0.97663035, 0.70248293, 0.43455671, 0.04345778]],

       [[0.9915365 , 0.79284291, 0.05829784, 0.16471109, 0.45846866],
        [0.75619103, 0.45090565, 0.74805334, 0.53043513, 0.3916003 ],
        [0.10701293, 0.69073703, 0.81346314, 0.37498441, 0.39341893]]])

#### 4. Print *a*.


In [17]:
# your code here
a

array([[[0.02231172, 0.29945747, 0.00463107, 0.48132289, 0.95170162],
        [0.84221344, 0.25186719, 0.48949999, 0.03256431, 0.8463534 ],
        [0.21041523, 0.00141905, 0.27183837, 0.34558973, 0.0278985 ]],

       [[0.26875114, 0.1997851 , 0.26133733, 0.85504941, 0.45061267],
        [0.65189698, 0.7876542 , 0.89486001, 0.27877477, 0.71740643],
        [0.0271388 , 0.84422612, 0.1650754 , 0.12490619, 0.00570087]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [18]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [19]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [22]:
# your code here
print(a.shape)
print(b.shape)
a.shape == b.shape

(2, 3, 5)
(5, 2, 3)


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [26]:
# your answer here
k = a + b
# ValueError: operands could not be broadcast together with shapes
# Não é possóvel somar devido ao tamanho das matrizes não permitirem se somar. 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the reshaped array to variable *c*.

In [25]:
# your code here
c=np.ones(a.shape)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [61]:
# your code/answer here
d = a + c
d
#Porque as matrizes possuem a mesma dimensão

array([[[63., 90., 83., 26., 57.],
        [85., 67., 39., 78., 94.],
        [12., 69., 79.,  7., 69.]],

       [[37., 31., 47., 24., 50.],
        [67., 52., 65., 87., 44.],
        [67., 42., 57., 32., 17.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [62]:
# your code/answer here
print(a)
print(" ------------------------------------------------------")
print(d)
# 'd' é a matriz igual a matriz 'a' somado a 1 em cada elemento 

[[[62 89 82 25 56]
  [84 66 38 77 93]
  [11 68 78  6 68]]

 [[36 30 46 23 49]
  [66 51 64 86 43]
  [66 41 56 31 16]]]
 ------------------------------------------------------
[[[63. 90. 83. 26. 57.]
  [85. 67. 39. 78. 94.]
  [12. 69. 79.  7. 69.]]

 [[37. 31. 47. 24. 50.]
  [67. 52. 65. 87. 44.]
  [67. 42. 57. 32. 17.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [63]:
# your code here
e = a * c
e

array([[[62., 89., 82., 25., 56.],
        [84., 66., 38., 77., 93.],
        [11., 68., 78.,  6., 68.]],

       [[36., 30., 46., 23., 49.],
        [66., 51., 64., 86., 43.],
        [66., 41., 56., 31., 16.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [64]:
# your code/answer here
print(e is a)
# em relação aos valores são iguais porém em relação ao local e seu 'id' salvo na memória do pc não são iguais.

False


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [65]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max,d_min,d_mean)

94.0 7.0 54.56666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [66]:
# your code here
f=np.empty(d.shape)
f

array([[[25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25.]],

       [[25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [75]:
# your code here
z=d.copy()
print(z)


print(z.shape)
for i in range(z.shape[0]):
    for j in range(z.shape[1]):
        for k in range(z.shape[2]):
            if z[i,j,k] > d_min and z[i,j,k]<d_mean:
                f[i,j,k]=25
            elif z[i,j,k] > d_mean and z[i,j,k] < d_max:
                f[i,j,k] = 75
            elif z[i,j,k] ==d_mean:
                f[i,j,k] =50
            elif z[i,j,k] ==d_min:
                f[i,j,k]=0
            elif z[i,j,k] ==d_max:
                f[i,j,k]=100
            
print(f)
  



[[[63. 90. 83. 26. 57.]
  [85. 67. 39. 78. 94.]
  [12. 69. 79.  7. 69.]]

 [[37. 31. 47. 24. 50.]
  [67. 52. 65. 87. 44.]
  [67. 42. 57. 32. 17.]]]
(2, 3, 5)
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  75. 100.]
  [ 25.  75.  75.   0.  75.]]

 [[ 25.  25.  25.  25.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  25.  75.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [80]:
# your code here

z=np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
d_max = z.max()
d_min = z.min()
d_mean = z.mean()
print(d_max,d_min,d_mean)


print(z)
for i in range(z.shape[0]):
    for j in range(z.shape[1]):
        for k in range(z.shape[2]):
            if z[i,j,k] ==d_min:
                f[i,j,k]=0
            elif z[i,j,k] ==d_max:
                f[i,j,k]=100
            elif z[i,j,k] > d_min and z[i,j,k]<d_mean:
                f[i,j,k]=25
            elif z[i,j,k] > d_mean and z[i,j,k] < d_max:
                f[i,j,k] = 75
            elif z[i,j,k] ==d_mean:
                f[i,j,k] =50
            
            
print(f)




1.97066381 1.00656599 1.6175069086666667
[[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [98]:
# your code here

z=np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
d_max = z.max()
d_min = z.min()
d_mean = z.mean()
print(d_max,d_min,d_mean)


print(z)


#codigo que cria uma lista

VarAux=[]
for i in range(z.shape[0]):
    for j in range(z.shape[1]):
        for k in range(z.shape[2]):
            if z[i,j,k] ==d_min:
                VarAux.append('A')
            elif z[i,j,k] ==d_max:
                VarAux.append('E')
            elif z[i,j,k] > d_min and z[i,j,k]<d_mean:
                VarAux.append('B')
            elif z[i,j,k] > d_mean and z[i,j,k] < d_max:
                VarAux.append('D')
            elif z[i,j,k] ==d_mean:
                VarAux.append('C')
print(VarAux)




my_array =np.array(VarAux)
print("-----------------------------------------2")
print(my_array)







#for i in range(z.shape[0]):
#    for j in range(z.shape[1]):
#        for k in range(z.shape[2]):
#            if z[i,j,k] ==d_min:

            
            
#print(f)


1.97066381 1.00656599 1.6175069086666667
[[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]
['D', 'D', 'D', 'B', 'D', 'D', 'D', 'B', 'B', 'B', 'D', 'B', 'D', 'D', 'D', 'B', 'B', 'B', 'B', 'E', 'D', 'D', 'D', 'D', 'D', 'B', 'D', 'A', 'D', 'D']
-----------------------------------------2
['D' 'D' 'D' 'B' 'D' 'D' 'D' 'B' 'B' 'B' 'D' 'B' 'D' 'D' 'D' 'B' 'B' 'B'
 'B' 'E' 'D' 'D' 'D' 'D' 'D' 'B' 'D' 'A' 'D' 'D']
